export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const CREATE_ORDER_WITH_COD = "CREATE_ORDER_WITH_COD";
export const CREATE_ORDER_WITH_COD_SUCCESS = "CREATE_ORDER_WITH_COD_SUCCESS";
export const CREATE_ORDER_WITH_COD_FAILURE = "CREATE_ORDER_WITH_COD_FAILURE";

export const CREATE_ORDER_WITH_CASH = "CREATE_ORDER_WITH_CASH";
export const CREATE_ORDER_WITH_CASH_SUCCESS = "CREATE_ORDER_WITH_CASH_SUCCESS";
export const CREATE_ORDER_WITH_CASH_FAILURE = "CREATE_ORDER_WITH_CASH_FAILURE";



export const GET_ALL_ORDERS_REQUEST = 'GET_ALL_ORDERS_REQUEST'
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS'
export const GET_ALL_ORDERS_FAILURE = 'GET_ALL_ORDERS_FAILURE'
