export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const CREATE_ORDER_WITH_COD = "CREATE_ORDER_WITH_COD";
export const CREATE_ORDER_WITH_COD_SUCCESS = "CREATE_ORDER_WITH_COD_SUCCESS";
export const CREATE_ORDER_WITH_COD_FAILURE = "CREATE_ORDER_WITH_COD_FAILURE";

export const CREATE_ORDER_WITH_CASH = "CREATE_ORDER_WITH_CASH";
export const CREATE_ORDER_WITH_CASH_SUCCESS = "CREATE_ORDER_WITH_CASH_SUCCESS";
export const CREATE_ORDER_WITH_CASH_FAILURE = "CREATE_ORDER_WITH_CASH_FAILURE";

export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAILURE = "GET_ALL_ORDERS_FAILURE";

export const GET_ORDER_BY_ID_REQUEST = "GET_ORDER_BY_ID_REQUEST";
export const GET_ORDER_BY_ID_SUCCESS = "GET_ORDER_BY_ID_SUCCESS";
export const GET_ORDER_BY_ID_FAILURE = "GET_ORDER_BY_ID_FAILURE";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_FAILURE = "DELETE_ORDER_FAILURE"

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST"
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS"
export const CREATE_REVIEW_FAILURE = "CREATE_REVIEW_FAILURE"
